### PR TITLE
feat: additional default loki labels

### PR DESCRIPTION
**Pull request by MonolithProjects**
# Description

This PR is adding new default labels for Vector Loki Sink to create a user experience similar to Promtail

## Type of change

- [ ] A bug fix (PR prefix `fix`)
- [x] A new feature (PR prefix `feat`)
- [ ] A code change that neither fixes a bug nor adds a feature (PR prefix `refactor`)
- [ ] Adding missing tests or correcting existing tests (PR prefix `test`)
- [ ] Changes that do not affect the meaning of the code like white-spaces, formatting, missing semi-colons, etc. (PR prefix `style`)
- [ ] Changes to our CI configuration files and scripts (PR prefix `ci`)
- [ ] Documentation only changes (PR prefix `docs`)

## How Has This Been Tested?

All labes/templates were in existing LARA deployment

### CODE REVIEW

**Review by dojci — CHANGES_REQUESTED** [review]
Please sync default labels with [promtail default configuration](https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml#L343):
image

**Comment by MonolithProjects** [comment]
Added and renamed labels to match the Promtail. To save some resouurces i excluded the `job` label as it is just a combination of pod and namespace.
image

**Comment by MonolithProjects** [comment]
wait a sec... i don't see the `app` label.

**Comment by MonolithProjects** [comment]
Resolved
image

**Review by dojci — CHANGES_REQUESTED** [review]
Please fix pipeline checks

**Comment by MonolithProjects** [comment]
done :slightly_smiling_face:

**Review by dojci — APPROVED** [review]
LGTM

**Pull request merged**
